#!/usr/bin/env python3
"""Emit check_config.json for check_structure.py / check_content.py.

Both gates want a {docs, sources, notes} config: docs maps each TRANSLATED
unit id to its reading file, sources maps it to the parity source in data/zh.
A unit counts as translated once out/<id>_reading.md exists (the same rule the
builder uses). Regenerate this at the start of every batch's check pass so the
config never lags behind what has actually been translated.

Usage: gen_check_config.py            (writes check_config.json at the root)
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    book = json.load(open(os.path.join(ROOT, "book.json"), encoding="utf-8"))
    docs, sources = {}, {}
    for chap in book.get("structure", []):
        cid = chap.get("id", "")
        if not cid.startswith("ch"):
            continue
        rd = os.path.join("out", "%s_reading.md" % cid)
        zh = os.path.join("data", "zh", "%s.txt" % cid)
        if os.path.exists(os.path.join(ROOT, rd)):
            docs[cid] = rd
            if os.path.exists(os.path.join(ROOT, zh)):
                sources[cid] = zh
    cfg = {
        "_README": "Generated by scripts/gen_check_config.py; do not hand-edit. "
                   "Lists translated units for check_structure.py and "
                   "check_content.py. Rerun the generator each batch.",
        "docs": docs,
        "sources": sources,
        "notes": "notes.json",
        "heading_depth": 1,
    }
    with open(os.path.join(ROOT, "check_config.json"), "w", encoding="utf-8") as fh:
        json.dump(cfg, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    print("wrote check_config.json: %d translated unit(s)" % len(docs))


if __name__ == "__main__":
    main()
