#!/bin/bash
# Register tic battery for the B09 de-archaizing pass. Usage: tics.sh chNN
cd /home/user/winston
f="out/$1_reading.md"
echo "########## $1 ##########"
echo "=== [dates] day-month order (-> month-day) ==="
grep -noE "\b([0-9]{1,2}) (January|February|March|April|May|June|July|August|September|October|November|December)\b" "$f"
echo "=== [antique fn-words] ==="
grep -noiE "\b(thereupon|whereupon|at length|presently|ere long|before long|of a morning|of an evening|was wont to|had no wish to|made bold to|come what may|for all that|and no mistake|still less could|let slip|of late|forthwith)\b" "$f"
echo "=== [could only / not but / not help / cannot help] ==="
grep -noE "(could only|could not but|could not help|cannot help|not help but)" "$f"
echo "=== [pivots 即/也就是] ==="
grep -noE "(that is to say|which was to say|in other words| namely[ ,])" "$f"
echo "=== [de-nominalize 'the [gerund] of'] ==="
grep -noE "[Tt]he [a-z]+(ing|ment) of the" "$f"
echo "=== [quote-tag archaisms] ==="
grep -noE "(disclosed many years later|in his lifetime|in his later years|recalled in his later years|said in his lifetime|would recall|many years later,)" "$f"
echo "=== [and the rest] ==="
grep -noE "and the rest" "$f"
echo "=== [narration ellipsis] ==="
grep -noE "\.\.\.[^\"]" "$f"
echo "=== [sentence-initial numeral] ==="
grep -noE "^[0-9]" "$f"
echo "=== [in the end inside a question] ==="
grep -noE "in the end[^.]*\?" "$f"
